# These are supported funding model platforms

github: China-Fan # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: We don't have this. # Replace with a single Patreon username
open_collective: We don't have this. # Replace with a single Open Collective username
ko_fi: We don't have this. # Replace with a single Ko-fi username
tidelift: We don't have this. # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: We don't have this. # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: We don't have this. # Replace with a single Liberapay username
issuehunt: We don't have this. # Replace with a single IssueHunt username
lfx_crowdfunding: We don't have this. # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: We don't have this. # Replace with a single Polar username
buy_me_a_coffee: We don't have this. # Replace with a single Buy Me a Coffee username
thanks_dev: We don't have this. # Replace with a single thanks.dev username
custom: We don't have this. # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
